import processedSpells from "../assets/spells_processed.json";
import type { SpellClassName, SpellModel } from "./types";

/**
 * The processed spell data, generated by scripts/processSpellData.ts
 * This avoids parsing massive JSON files at runtime.
 */
export const spells: SpellModel[] = processedSpells as SpellModel[];

/**
 * Get all spells for a specific breed/class.
 */
export function getSpellsByClass(className: SpellClassName): SpellModel[] {
  return spells.filter((s) => s.class === className);
}

/**
 * Get a specific spell by ID.
 */
export function getSpellById(id: number): SpellModel | undefined {
  return spells.find((s) => s.id === id);
}

export function getAllSpells(): SpellModel[] {
  return spells;
}

export type { SpellModel };
